# -*- coding: utf-8 -*-
"""Traffic_Flow_Pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuBvvcr3Oro0YhriibGilmT7Wn82juaj

Install Required Libraries
"""

!pip install ucimlrepo pandas numpy matplotlib seaborn scikit-learn tensorflow xgboost

"""Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout
from ucimlrepo import fetch_ucirepo

"""Fetch Dataset"""

# Fetch dataset
metro_interstate_traffic_volume = fetch_ucirepo(id=492)

# Features and target
X = metro_interstate_traffic_volume.data.features
y = metro_interstate_traffic_volume.data.targets

# Combine features and target for EDA
data = pd.concat([X, y], axis=1)

"""Display Dataset Information"""

print(metro_interstate_traffic_volume.metadata)
print(metro_interstate_traffic_volume.variables)

"""Check for Missing Values"""

print(data.isnull().sum())

data['holiday'] = data['holiday'].fillna('None')

"""Handle Missing Values"""

# Handle Missing Values for numeric columns only
for column in data.select_dtypes(include=np.number).columns:
    data.loc[:, column] = data[column].fillna(data[column].median())

print(data.isnull().sum())

"""Exploratory Data Analysis (EDA) - Summary Statistics"""

print(data.describe())

"""EDA - Traffic Volume Distribution"""

plt.figure(figsize=(10, 6))
sns.histplot(data['traffic_volume'], bins=50, kde=True)
plt.title('Traffic Volume Distribution')
plt.xlabel('Traffic Volume')
plt.ylabel('Frequency')
plt.show()